include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**, lib/**.g.dart, lib/generated_plugin_registrant.dart]

linter:
  rules:
    prefer_single_quotes: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    require_trailing_commas: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    depend_on_referenced_packages: false
    use_build_context_synchronously: false
